### ISSUE TITLE
new() does not allow setting config values

### ISSUE THREAD

**Issue by tomk3003** [jhthorsen/test-mojo-role-selenium#1]
The role Test::Mojo::Role::Selenium overrides new from Test::Mojo, which results in loosing the option to specify special configuration values.

Changing:
 
`
return $self->app(ref $app ? $app : Mojo::Server->new->build_app($app));
`

to

`
my @args = @_ ? {config => {config_override => 1, %{shift()}}} : ();
return $self->app(
  ref $app ? $app : Mojo::Server->new->build_app($app, @args));
`

resolves that.

**Comment by jhthorsen** [comment]
Thanks for reporting in!

Could you provide a PR and a test?

**Comment by tomk3003** [comment]
I can do that, but I am not sure whether overwriting new in a role is the best way to go. 
Would doing a `after new => sub {...}` be ok or is the dependency on Class::Method::Modifiers not desirable?

**Comment by tomk3003** [comment]
make that `around` instead of `after`

**Comment by tomk3003** [comment]
Forget it, `around` will not work, I'll go forward with modifying new.
