### ISSUE TITLE
version 0.12 is not correctly listed on CPAN

### ISSUE THREAD

**Issue by tomk3003** [jhthorsen/test-mojo-role-selenium#2]
Version 0.12 is not listed in 02packages.details.txt and a search (either cpan or metacpan) will always point to version 0.11.
But 0.12 is available for selection afterwards.

**Comment by jhthorsen** [comment]
Looks like @marcusramberg was not a co-author. I've changed the permissions now. I will also make another release later today to make sure 0.13 will be indexed.
