### ISSUE TITLE
wait_for does not work

### ISSUE THREAD

**Issue by tim-2** [jhthorsen/test-mojo-role-selenium#5]
When using wait_for with a selector string Selenium::Remote::Driver fails with this error:
```
Error while executing command: unknown error: 'ms' must be a double
  (Session info: chrome=63.0.3239.108)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.15.0-52-generic x86_64) at /home/karsten/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Selenium/Remote/Driver.pm line 403.
 at /home/tim/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Selenium/Remote/Driver.pm line 353.
```

> Test::Mojo::Role::Selenium is up to date. (0.16)
> Selenium::Remote::Driver is up to date. (1.33)

**Comment by jhthorsen** [comment]
I’ve noticed the same, but haven’t had time to dig deep. Which backend do you use?

**Comment by tim-2** [comment]
Perl        (v5.28.0, linux)
Mojolicious (8.18, Supervillain)

**Comment by tim-2** [comment]
I looks like this is a Selenium::Remote::Driver issue: https://github.com/teodesian/Selenium-Remote-Driver/issues/427

**Comment by jhthorsen** [comment]
Awesome! Thank you 👍
