### ISSUE TITLE
Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by tim-2** [jhthorsen/test-mojo-role-selenium#7]
I get this error when calling `click_ok` on any element:

> Error while executing command: unknown command: unknown command: Cannot call non W3C standard command while in W3C mode

If I call driver methods directly it works:
`if(my $e = $driver->find_element_by_id('button')) { $e->click }`

`ChromeDriver 78.0.3904.108 (4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889})`

**Comment by jhthorsen** [comment]
I think you have to report this error to https://github.com/teodesian/Selenium-Remote-Driver.

Please let me know if you can't reproduce it with a plain instance of Selenium-Remote-Driver, and also how to fix/reproduce it.
